- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/Project

    - name: tag image
      command: docker tag petstore:latest amined2001/Project:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: amined2001
        password: <password>

    - name: Push image
      command: docker push amined2001/Project:latest 

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 amined2001/Project:latest 
